# Generated by Django 4.2.27 on 2026-01-25 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('news', '0001_initial'),
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='news.newsarticle'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='markets.company'),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topcontent',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_rankings', to='news.newsarticle'),
        ),
        migrations.AddIndex(
            model_name='systemhealth',
            index=models.Index(fields=['-timestamp'], name='analytics_s_timesta_fcd559_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scrapingmetrics',
            unique_together={('spider_type', 'date')},
        ),
        migrations.AddField(
            model_name='geographicanalytics',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='geography.country'),
        ),
        migrations.AddField(
            model_name='contentperformance',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='news.newsarticle'),
        ),
        migrations.AddField(
            model_name='articleanalytics',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='news.newsarticle'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', '-created_at'], name='analytics_u_user_id_e2feae_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['activity_type', '-created_at'], name='analytics_u_activit_d4e03e_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['article', '-created_at'], name='analytics_u_article_a2c66e_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['-created_at'], name='analytics_u_created_8f4294_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topcontent',
            unique_together={('period', 'rank', 'metric_type')},
        ),
        migrations.AlterUniqueTogether(
            name='geographicanalytics',
            unique_together={('date', 'country')},
        ),
        migrations.AddIndex(
            model_name='articleanalytics',
            index=models.Index(fields=['date', 'hour'], name='analytics_a_date_6acc30_idx'),
        ),
        migrations.AddIndex(
            model_name='articleanalytics',
            index=models.Index(fields=['article', 'date'], name='analytics_a_article_461853_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articleanalytics',
            unique_together={('article', 'date', 'hour')},
        ),
    ]
