# Generated by Django 4.2.27 on 2026-01-25 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Columnist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('display_name', models.CharField(help_text='Byline name (can differ from legal name)', max_length=200, verbose_name='Display Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('columnist_type', models.CharField(choices=[('staff', 'Staff Writer'), ('columnist', 'Columnist'), ('analyst', 'Market Analyst'), ('contributor', 'Guest Contributor'), ('editor', 'Editor')], default='contributor', max_length=20, verbose_name='Type')),
                ('title', models.CharField(blank=True, help_text='e.g., Senior Market Analyst, Economics Editor', max_length=200, verbose_name='Professional Title')),
                ('organization', models.CharField(blank=True, help_text='Current employer or affiliation', max_length=200, verbose_name='Organization')),
                ('short_bio', models.CharField(help_text='Brief bio for article bylines (max 300 chars)', max_length=300, verbose_name='Short Bio')),
                ('full_bio', models.TextField(blank=True, help_text='Detailed biography for profile page', verbose_name='Full Bio')),
                ('credentials', models.TextField(blank=True, help_text='Qualifications, certifications, education', verbose_name='Credentials')),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='columnists/headshots/', verbose_name='Headshot')),
                ('headshot_credit', models.CharField(blank=True, max_length=200, verbose_name='Photo Credit')),
                ('banner_image', models.ImageField(blank=True, help_text='Profile page banner', null=True, upload_to='columnists/banners/', verbose_name='Banner Image')),
                ('twitter_handle', models.CharField(blank=True, max_length=50, verbose_name='Twitter/X')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('website_url', models.URLField(blank=True, verbose_name='Personal Website')),
                ('email_public', models.EmailField(blank=True, help_text='Public contact email (different from account email)', max_length=254, verbose_name='Public Email')),
                ('primary_region', models.CharField(blank=True, help_text='Primary geographic coverage area', max_length=20, verbose_name='Primary Region')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('featured', 'Featured Expert')], default='pending', max_length=20, verbose_name='Verification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on columnists page prominently', verbose_name='Featured')),
                ('joined_date', models.DateField(blank=True, null=True, verbose_name='Joined Date')),
                ('show_article_count', models.BooleanField(default=True, verbose_name='Show Article Count')),
                ('allow_follow', models.BooleanField(default=True, verbose_name='Allow Following')),
                ('newsletter_enabled', models.BooleanField(default=False, help_text='Has personal newsletter subscribers can follow', verbose_name='Newsletter Enabled')),
            ],
            options={
                'verbose_name': 'Columnist',
                'verbose_name_plural': 'Columnists',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ExpertiseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Expertise Area')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Expertise Area',
                'verbose_name_plural': 'Expertise Areas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColumnistStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('total_articles', models.PositiveIntegerField(default=0)),
                ('articles_this_month', models.PositiveIntegerField(default=0)),
                ('articles_this_year', models.PositiveIntegerField(default=0)),
                ('total_views', models.BigIntegerField(default=0)),
                ('views_this_month', models.BigIntegerField(default=0)),
                ('avg_views_per_article', models.PositiveIntegerField(default=0)),
                ('total_followers', models.PositiveIntegerField(default=0)),
                ('avg_read_time', models.PositiveIntegerField(default=0, help_text='Average read time in seconds')),
                ('engagement_score', models.DecimalField(decimal_places=2, default=0, help_text='Calculated engagement score (0-100)', max_digits=5)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('columnist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='columnists.columnist')),
            ],
            options={
                'verbose_name': 'Columnist Stats',
                'verbose_name_plural': 'Columnist Stats',
            },
        ),
        migrations.AddField(
            model_name='columnist',
            name='expertise',
            field=models.ManyToManyField(blank=True, related_name='columnists', to='columnists.expertisearea'),
        ),
        migrations.AddField(
            model_name='columnist',
            name='primary_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='columnists', to='geography.country'),
        ),
        migrations.AddField(
            model_name='columnist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='columnist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Column Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='columns/', verbose_name='Cover Image')),
                ('frequency', models.CharField(blank=True, help_text='e.g., Weekly, Daily, Monthly', max_length=50, verbose_name='Frequency')),
                ('publish_day', models.CharField(blank=True, help_text='e.g., Monday, First of Month', max_length=20, verbose_name='Publish Day')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium Only')),
                ('columnist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='columnists.columnist')),
            ],
            options={
                'verbose_name': 'Column',
                'verbose_name_plural': 'Columns',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColumnistFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('columnist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='columnists.columnist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnist_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Columnist Follow',
                'verbose_name_plural': 'Columnist Follows',
                'unique_together': {('user', 'columnist')},
            },
        ),
        migrations.AddIndex(
            model_name='columnist',
            index=models.Index(fields=['slug'], name='columnists__slug_aaa383_idx'),
        ),
        migrations.AddIndex(
            model_name='columnist',
            index=models.Index(fields=['columnist_type', 'is_active'], name='columnists__columni_4b957d_idx'),
        ),
        migrations.AddIndex(
            model_name='columnist',
            index=models.Index(fields=['verification_status'], name='columnists__verific_236908_idx'),
        ),
    ]
