# Generated by Django 5.0.14 on 2026-02-04 17:07

import ckeditor_uploader.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Industry Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50, verbose_name='Icon')),
                ('color', models.CharField(default='#FF6B00', help_text='Hex color code', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='industries/', verbose_name='Cover Image')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='research_in_slug_8d8c79_idx'), models.Index(fields=['is_active', 'is_featured'], name='research_in_is_acti_50d6ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResearchReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Subtitle')),
                ('abstract', models.TextField(help_text='Executive summary of the research', verbose_name='Abstract')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Full research report content', verbose_name='Full Content')),
                ('key_findings', models.JSONField(blank=True, default=list, help_text='List of key findings/takeaways', verbose_name='Key Findings')),
                ('methodology', models.TextField(blank=True, help_text='Research methodology description', verbose_name='Methodology')),
                ('data_sources', models.TextField(blank=True, help_text='Sources of data used in research', verbose_name='Data Sources')),
                ('report_type', models.CharField(choices=[('whitepaper', 'Whitepaper'), ('analysis', 'Market Analysis'), ('outlook', 'Sector Outlook'), ('country', 'Country Report'), ('quarterly', 'Quarterly Review'), ('annual', 'Annual Report'), ('special', 'Special Report')], default='analysis', max_length=20, verbose_name='Report Type')),
                ('external_authors', models.JSONField(blank=True, default=list, help_text='List of external author objects with name, title, organization', verbose_name='External Authors')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='research/covers/', verbose_name='Cover Image')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='research/pdfs/', verbose_name='PDF File')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Published At')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_premium', models.BooleanField(default=True, help_text='Requires subscription to download full report', verbose_name='Premium Content')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('read_time_minutes', models.PositiveIntegerField(default=15, verbose_name='Read Time (minutes)')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='Page Count')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('contributing_authors', models.ManyToManyField(blank=True, related_name='contributed_research_reports', to=settings.AUTH_USER_MODEL)),
                ('countries', models.ManyToManyField(blank=True, related_name='research_reports', to='geography.country')),
                ('industries', models.ManyToManyField(blank=True, related_name='research_reports', to='research.industry')),
                ('lead_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_research_reports', to=settings.AUTH_USER_MODEL)),
                ('related_companies', models.ManyToManyField(blank=True, related_name='research_reports', to='markets.company')),
            ],
            options={
                'verbose_name': 'Research Report',
                'verbose_name_plural': 'Research Reports',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_downloads', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='research.researchreport')),
            ],
            options={
                'verbose_name': 'Research Download',
                'verbose_name_plural': 'Research Downloads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Topic Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50, verbose_name='Icon')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Display prominently on homepage', verbose_name='Featured')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtopics', to='research.topic')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='researchreport',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='research_reports', to='research.topic'),
        ),
        migrations.CreateModel(
            name='ResearchRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('relation_type', models.CharField(blank=True, help_text="e.g., 'follow-up', 'related', 'supersedes'", max_length=50, verbose_name='Relation Type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('related_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='research.researchreport')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='research.researchreport')),
            ],
            options={
                'verbose_name': 'Related Research',
                'verbose_name_plural': 'Related Research',
                'ordering': ['order'],
                'unique_together': {('report', 'related_report')},
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['slug'], name='research_to_slug_333855_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_active', 'is_featured'], name='research_to_is_acti_a13c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='researchreport',
            index=models.Index(fields=['status', 'published_at'], name='research_re_status_108f41_idx'),
        ),
        migrations.AddIndex(
            model_name='researchreport',
            index=models.Index(fields=['report_type', 'status'], name='research_re_report__fab1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='researchreport',
            index=models.Index(fields=['is_featured', 'status'], name='research_re_is_feat_5d4ae2_idx'),
        ),
    ]
