# Generated by Django 5.0.14 on 2026-02-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchreport',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='External URL for cover image (fallback if no uploaded image)', max_length=500, verbose_name='Cover Image URL'),
        ),
    ]
