# Generated by Django 5.0.14 on 2026-04-15 09:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchreport_cover_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchreport',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Optional — leave empty if the research is contained in the PDF', verbose_name='Full Content'),
        ),
    ]
