# Generated by Django 5.0.14 on 2026-04-15 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_alter_researchreport_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, verbose_name='Referrer')),
                ('time_on_page', models.PositiveIntegerField(default=0, verbose_name='Time on Page (seconds)')),
                ('country', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Country')),
                ('country_name', models.CharField(blank=True, max_length=80, verbose_name='Country Name')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='City')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Region')),
                ('source', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Research View',
                'verbose_name_plural': 'Research Views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='researchdownload',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='researchdownload',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='researchdownload',
            name='country_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Country Name'),
        ),
        migrations.AddIndex(
            model_name='researchdownload',
            index=models.Index(fields=['-created_at'], name='research_re_created_3df8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='researchdownload',
            index=models.Index(fields=['report', '-created_at'], name='research_re_report__d551f1_idx'),
        ),
        migrations.AddField(
            model_name='researchview',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='research.researchreport'),
        ),
        migrations.AddField(
            model_name='researchview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='researchview',
            index=models.Index(fields=['-created_at'], name='research_re_created_dd4eca_idx'),
        ),
        migrations.AddIndex(
            model_name='researchview',
            index=models.Index(fields=['report', '-created_at'], name='research_re_report__688272_idx'),
        ),
        migrations.AddIndex(
            model_name='researchview',
            index=models.Index(fields=['country', '-created_at'], name='research_re_country_fcd79e_idx'),
        ),
    ]
