# Generated by Django 5.0.14 on 2026-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_researchview_researchdownload_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
