# Generated by Django 5.0.14 on 2026-04-16 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_researchreport_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='researchreport',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes Count'),
        ),
        migrations.AddField(
            model_name='researchreport',
            name='saves_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Saves Count'),
        ),
        migrations.CreateModel(
            name='ResearchSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('country', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Country')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='research.researchreport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Save',
                'verbose_name_plural': 'Research Saves',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('country', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Country')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='research.researchreport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Like',
                'verbose_name_plural': 'Research Likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report', '-created_at'], name='research_re_report__798126_idx'), models.Index(fields=['user', '-created_at'], name='research_re_user_id_60a859_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='researchlike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('report', 'user'), name='unique_research_like_per_user'),
        ),
        migrations.AddConstraint(
            model_name='researchlike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('session_key', ''), _negated=True)), fields=('report', 'session_key'), name='unique_research_like_per_session'),
        ),
        migrations.AddIndex(
            model_name='researchsave',
            index=models.Index(fields=['report', '-created_at'], name='research_re_report__5a443b_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsave',
            index=models.Index(fields=['user', '-created_at'], name='research_re_user_id_cfb163_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchsave',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('report', 'user'), name='unique_research_save_per_user'),
        ),
        migrations.AddConstraint(
            model_name='researchsave',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('session_key', ''), _negated=True)), fields=('report', 'session_key'), name='unique_research_save_per_session'),
        ),
    ]
