# Generated by Django 5.0.14 on 2026-02-09 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed_authors',
            field=models.ManyToManyField(blank=True, help_text='Authors the user is following', related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
