# Generated by Django 5.0.14 on 2026-04-17 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_followed_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('bio', models.TextField(blank=True, max_length=1000, verbose_name='Bio')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title / Role')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Organization')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='writers/', verbose_name='Avatar')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='Avatar URL')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='X / Twitter Handle')),
                ('linkedin', models.URLField(blank=True, max_length=300, verbose_name='LinkedIn URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.OneToOneField(blank=True, help_text='Link to platform account if the writer has one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Writer',
                'verbose_name_plural': 'Writers',
                'ordering': ['full_name'],
            },
        ),
    ]
