# Generated by Django 5.0.14 on 2026-05-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='email_public',
            field=models.BooleanField(default=False, help_text="When on, the writer's email is included in the public byline so readers can reach out directly.", verbose_name='Show email on byline'),
        ),
    ]
