# Generated by Django 5.0.14 on 2026-07-29 12:18

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text="Who this key belongs to, e.g. 'Bard Santner website'", max_length=200, verbose_name='Partner name')),
                ('key', models.CharField(db_index=True, default=apps.core.models._generate_partner_key, max_length=64, unique=True, verbose_name='Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('allowed_origins', models.TextField(blank=True, help_text='Optional comma-separated list of origins for CORS, e.g. https://bardsantner.com. Leave blank to allow any origin (content is public/read-only).', verbose_name='Allowed origins')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last used')),
                ('request_count', models.PositiveBigIntegerField(default=0, verbose_name='Requests served')),
            ],
            options={
                'verbose_name': 'Partner API Key',
                'verbose_name_plural': 'Partner API Keys',
                'ordering': ['name'],
            },
        ),
    ]
