# Generated by Django 4.2.27 on 2026-01-25 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('alert_type', models.CharField(choices=[('above', 'Price Above'), ('below', 'Price Below'), ('percent_change', 'Percent Change')], default='above', max_length=20, verbose_name='Alert Type')),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Target Price')),
                ('target_percent', models.DecimalField(blank=True, decimal_places=2, help_text='For percent_change alerts', max_digits=8, null=True, verbose_name='Target Percent Change')),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Triggered At')),
                ('triggered_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Triggered Price')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notification Sent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='markets.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Price Alert',
                'verbose_name_plural': 'Price Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='engagement__user_id_9a33ca_idx'), models.Index(fields=['company', 'status'], name='engagement__company_e0641d_idx'), models.Index(fields=['status', 'alert_type'], name='engagement__status_5886a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('notification_type', models.CharField(choices=[('price_alert', 'Price Alert'), ('breaking_news', 'Breaking News'), ('earnings', 'Earnings Report'), ('watchlist', 'Watchlist Update'), ('system', 'System')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data (company_id, article_id, etc.)', verbose_name='Data')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='engagement__user_id_6fcaa4_idx'), models.Index(fields=['user', 'notification_type'], name='engagement__user_id_3295bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('email', models.EmailField(db_index=True, help_text='Email for non-authenticated subscribers', max_length=254, verbose_name='Email')),
                ('newsletter_type', models.CharField(choices=[('morning_brief', 'Morning Brief'), ('evening_wrap', 'Evening Wrap'), ('weekly_digest', 'Weekly Digest'), ('breaking_news', 'Breaking News'), ('earnings', 'Earnings Alerts')], default='morning_brief', max_length=20, verbose_name='Newsletter Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('verification_token', models.CharField(blank=True, max_length=64, verbose_name='Verification Token')),
                ('unsubscribe_token', models.CharField(blank=True, max_length=64, verbose_name='Unsubscribe Token')),
                ('preferred_exchanges', models.JSONField(blank=True, default=list, help_text='List of exchange codes to include', verbose_name='Preferred Exchanges')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (if logged in)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'indexes': [models.Index(fields=['email', 'is_active'], name='engagement__email_fb6f64_idx'), models.Index(fields=['newsletter_type', 'is_active'], name='engagement__newslet_7c00c0_idx')],
                'unique_together': {('email', 'newsletter_type')},
            },
        ),
    ]
