# Generated by Django 5.0.14 on 2026-02-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='newsletter_type',
            field=models.CharField(choices=[('morning_brief', 'Morning Brief'), ('evening_wrap', 'Evening Wrap'), ('weekly_digest', 'Weekly Digest'), ('breaking_news', 'Breaking News'), ('earnings', 'Earnings Alerts'), ('finance_africa_quarterly', 'Finance Africa Quarterly'), ('finance_africa_insights', 'Finance Africa Insights'), ('afrifin_analytics', 'AfriFin Analytics')], default='morning_brief', max_length=30, verbose_name='Newsletter Type'),
        ),
    ]
