# Generated by Django 4.2.27 on 2026-01-25 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('revision_number', models.PositiveIntegerField(verbose_name='Revision Number')),
                ('revision_type', models.CharField(choices=[('create', 'Created'), ('edit', 'Edited'), ('status', 'Status Change'), ('publish', 'Published'), ('unpublish', 'Unpublished'), ('restore', 'Restored'), ('autosave', 'Auto-saved')], default='edit', max_length=20, verbose_name='Type')),
                ('headline', models.CharField(max_length=500, verbose_name='Headline')),
                ('subheadline', models.CharField(blank=True, max_length=500, verbose_name='Subheadline')),
                ('content', models.TextField(verbose_name='Content')),
                ('excerpt', models.TextField(blank=True, verbose_name='Excerpt')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('metadata_snapshot', models.JSONField(default=dict, help_text='Snapshot of article metadata at revision time', verbose_name='Metadata')),
                ('change_summary', models.CharField(blank=True, max_length=500, verbose_name='Change Summary')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Word Count')),
                ('char_count', models.PositiveIntegerField(default=0, verbose_name='Character Count')),
            ],
            options={
                'verbose_name': 'Article Revision',
                'verbose_name_plural': 'Article Revisions',
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='BucketArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured in Bucket')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Bucket Article',
                'verbose_name_plural': 'Bucket Articles',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContentBucket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Bucket Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('bucket_type', models.CharField(choices=[('campaign', 'Campaign'), ('series', 'Series'), ('theme', 'Theme'), ('event', 'Event Coverage'), ('section', 'Section'), ('archive', 'Archive')], default='theme', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('scheduled', 'Scheduled'), ('archived', 'Archived'), ('draft', 'Draft')], default='draft', max_length=20, verbose_name='Status')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher = more important', verbose_name='Priority')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50, verbose_name='Icon')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='buckets/covers/', verbose_name='Cover Image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_public', models.BooleanField(default=True, help_text='Visible to readers', verbose_name='Public')),
            ],
            options={
                'verbose_name': 'Content Bucket',
                'verbose_name_plural': 'Content Buckets',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContentCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('slot_type', models.CharField(choices=[('article', 'Article'), ('newsletter', 'Newsletter'), ('social', 'Social Media'), ('video', 'Video'), ('podcast', 'Podcast')], default='article', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('published', 'Published'), ('skipped', 'Skipped')], default='planned', max_length=20, verbose_name='Status')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='Scheduled Time')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Recurring')),
                ('recurrence_rule', models.CharField(blank=True, help_text='RRULE format', max_length=100, verbose_name='Recurrence Rule')),
            ],
            options={
                'verbose_name': 'Content Calendar',
                'verbose_name_plural': 'Content Calendar',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='EditorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('activity_type', models.CharField(choices=[('article_create', 'Created Article'), ('article_edit', 'Edited Article'), ('article_publish', 'Published Article'), ('article_unpublish', 'Unpublished Article'), ('article_delete', 'Deleted Article'), ('assign_create', 'Created Assignment'), ('assign_complete', 'Completed Assignment'), ('note_create', 'Added Note'), ('note_resolve', 'Resolved Note'), ('bucket_create', 'Created Bucket'), ('bucket_modify', 'Modified Bucket'), ('login', 'Logged In'), ('bulk', 'Bulk Action')], max_length=30, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'Editor Activity',
                'verbose_name_plural': 'Editor Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('assignment_type', models.CharField(choices=[('write', 'Write Article'), ('edit', 'Edit Article'), ('review', 'Review Article'), ('proofread', 'Proofread'), ('fact_check', 'Fact Check')], default='write', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher = more urgent', verbose_name='Priority')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('submission_notes', models.TextField(blank=True, verbose_name='Submission Notes')),
            ],
            options={
                'verbose_name': 'Editorial Assignment',
                'verbose_name_plural': 'Editorial Assignments',
                'ordering': ['-priority', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='EditorialNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('note_type', models.CharField(choices=[('comment', 'Comment'), ('suggestion', 'Suggestion'), ('issue', 'Issue'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('question', 'Question')], default='comment', max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20, verbose_name='Status')),
                ('content', models.TextField(verbose_name='Note')),
                ('content_reference', models.TextField(blank=True, help_text='Quoted text from article being referenced', verbose_name='Referenced Text')),
                ('position_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='Start Position')),
                ('position_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='End Position')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Resolution Note')),
            ],
            options={
                'verbose_name': 'Editorial Note',
                'verbose_name_plural': 'Editorial Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
