# Generated by Django 4.2.27 on 2026-01-25 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialnote',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_notes', to='news.newsarticle'),
        ),
        migrations.AddField(
            model_name='editorialnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_notes_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editorialnote',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='editorial.editorialnote'),
        ),
        migrations.AddField(
            model_name='editorialnote',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editorialassignment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='news.newsarticle'),
        ),
        migrations.AddField(
            model_name='editorialassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editorialassignment',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editoractivity',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='news.newsarticle'),
        ),
        migrations.AddField(
            model_name='editoractivity',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_targeted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editoractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentcalendar',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_slots', to='news.newsarticle'),
        ),
        migrations.AddField(
            model_name='contentcalendar',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentcalendar',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_slots', to='editorial.contentbucket'),
        ),
        migrations.AddField(
            model_name='contentcalendar',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_slots_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentbucket',
            name='assigned_editors',
            field=models.ManyToManyField(blank=True, related_name='assigned_buckets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentbucket',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_buckets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentbucket',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='editorial.contentbucket'),
        ),
        migrations.AddField(
            model_name='bucketarticle',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bucketarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_buckets', to='news.newsarticle'),
        ),
        migrations.AddField(
            model_name='bucketarticle',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_articles', to='editorial.contentbucket'),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='news.newsarticle'),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='editorialnote',
            index=models.Index(fields=['article', 'status'], name='editorial_e_article_6ce415_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialnote',
            index=models.Index(fields=['author', '-created_at'], name='editorial_e_author__c50cda_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialassignment',
            index=models.Index(fields=['assignee', 'status'], name='editorial_e_assigne_77ea91_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialassignment',
            index=models.Index(fields=['article', 'assignment_type'], name='editorial_e_article_5edc72_idx'),
        ),
        migrations.AddIndex(
            model_name='editoractivity',
            index=models.Index(fields=['user', '-created_at'], name='editorial_e_user_id_922b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='editoractivity',
            index=models.Index(fields=['activity_type', '-created_at'], name='editorial_e_activit_130f20_idx'),
        ),
        migrations.AddIndex(
            model_name='editoractivity',
            index=models.Index(fields=['article', '-created_at'], name='editorial_e_article_b589c9_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcalendar',
            index=models.Index(fields=['scheduled_date', 'status'], name='editorial_c_schedul_95c0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcalendar',
            index=models.Index(fields=['assigned_to', 'status'], name='editorial_c_assigne_f01bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='contentbucket',
            index=models.Index(fields=['slug'], name='editorial_c_slug_769b26_idx'),
        ),
        migrations.AddIndex(
            model_name='contentbucket',
            index=models.Index(fields=['bucket_type', 'status'], name='editorial_c_bucket__3d5cd9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bucketarticle',
            unique_together={('bucket', 'article')},
        ),
        migrations.AddIndex(
            model_name='articlerevision',
            index=models.Index(fields=['article', '-revision_number'], name='editorial_a_article_2ee2b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articlerevision',
            unique_together={('article', 'revision_number')},
        ),
    ]
