# Generated by Django 4.2.27 on 2026-01-25 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Portfolio Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('portfolio_type', models.CharField(choices=[('personal', 'Personal'), ('retirement', 'Retirement'), ('trading', 'Trading'), ('paper', 'Paper Trading'), ('watch', 'Watchlist Only')], default='personal', max_length=20, verbose_name='Type')),
                ('base_currency', models.CharField(choices=[('ZAR', 'South African Rand'), ('USD', 'US Dollar'), ('BWP', 'Botswana Pula'), ('ZWL', 'Zimbabwean Dollar'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('EGP', 'Egyptian Pound')], default='ZAR', max_length=3, verbose_name='Base Currency')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Portfolio')),
                ('is_public', models.BooleanField(default=False, help_text='Allow others to view this portfolio', verbose_name='Public')),
                ('show_values', models.BooleanField(default=True, help_text='Display monetary values', verbose_name='Show Values')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cash Balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('split', 'Stock Split'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('deposit', 'Cash Deposit'), ('withdrawal', 'Cash Withdrawal')], max_length=20, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Transaction Date')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Price per Share')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Amount')),
                ('currency', models.CharField(default='ZAR', max_length=3, verbose_name='Currency')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commission')),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Other Fees')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('tax_lot_id', models.CharField(blank=True, max_length=50, verbose_name='Tax Lot ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='markets.company')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantity')),
                ('average_cost', models.DecimalField(decimal_places=4, help_text='Average cost per share', max_digits=15, verbose_name='Average Cost')),
                ('first_purchase_date', models.DateField(verbose_name='First Purchase')),
                ('last_transaction_date', models.DateField(verbose_name='Last Transaction')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='markets.company')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['company__symbol'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('date', models.DateField(verbose_name='Date')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Value')),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cash Balance')),
                ('positions_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Positions Value')),
                ('day_change', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Day Change')),
                ('day_change_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Day Change %')),
                ('position_count', models.PositiveIntegerField(default=0, verbose_name='Positions')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Snapshot',
                'verbose_name_plural': 'Portfolio Snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('return_1d', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('return_1w', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('return_1m', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('return_3m', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('return_ytd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('return_1y', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('return_all', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('volatility', models.DecimalField(decimal_places=4, default=0, help_text='Annualized standard deviation', max_digits=8, verbose_name='Volatility')),
                ('sharpe_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Sharpe Ratio')),
                ('beta', models.DecimalField(decimal_places=4, default=1, max_digits=8, verbose_name='Beta')),
                ('total_dividends_received', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Dividends')),
                ('dividend_yield', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Dividend Yield')),
                ('best_day', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('best_day_date', models.DateField(blank=True, null=True)),
                ('worst_day', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('worst_day_date', models.DateField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Performance',
                'verbose_name_plural': 'Portfolio Performance',
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('dividend_type', models.CharField(choices=[('cash', 'Cash Dividend'), ('stock', 'Stock Dividend'), ('special', 'Special Dividend')], default='cash', max_length=20, verbose_name='Type')),
                ('ex_date', models.DateField(verbose_name='Ex-Dividend Date')),
                ('pay_date', models.DateField(verbose_name='Payment Date')),
                ('shares_held', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Shares Held')),
                ('dividend_per_share', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Dividend per Share')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Gross Amount')),
                ('tax_withheld', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax Withheld')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Net Amount')),
                ('currency', models.CharField(default='ZAR', max_length=3, verbose_name='Currency')),
                ('is_reinvested', models.BooleanField(default=False, verbose_name='Reinvested')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_payments', to='markets.company')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='portfolio.portfolio')),
                ('reinvestment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividend_reinvestment', to='portfolio.transaction')),
            ],
            options={
                'verbose_name': 'Dividend',
                'verbose_name_plural': 'Dividends',
                'ordering': ['-pay_date'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('target_buy_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Target Buy Price')),
                ('target_sell_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Target Sell Price')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('alert_on_target', models.BooleanField(default=True, verbose_name='Alert on Target')),
                ('alert_on_news', models.BooleanField(default=False, verbose_name='Alert on News')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='markets.company')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Watchlist Item',
                'verbose_name_plural': 'Watchlist Items',
                'unique_together': {('portfolio', 'company')},
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio', '-date'], name='portfolio_t_portfol_851a43_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['company', '-date'], name='portfolio_t_company_53d8be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('portfolio', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='portfoliosnapshot',
            unique_together={('portfolio', 'date')},
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', '-is_default'], name='portfolio_p_user_id_49148c_idx'),
        ),
    ]
