# Generated by Django 4.2.27 on 2026-01-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(max_length=100, verbose_name='City Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('is_capital', models.BooleanField(default=False, verbose_name='Is Capital')),
                ('is_financial_center', models.BooleanField(default=False, help_text='Major financial/business hub', verbose_name='Is Financial Center')),
                ('population', models.BigIntegerField(blank=True, null=True, verbose_name='Population')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('code', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 or alpha-3 code', max_length=3, unique=True, verbose_name='ISO Code')),
                ('name', models.CharField(max_length=100, verbose_name='Country Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('official_name', models.CharField(blank=True, max_length=200, verbose_name='Official Name')),
                ('region', models.CharField(choices=[('southern', 'Southern Africa'), ('eastern', 'East Africa'), ('western', 'West Africa'), ('northern', 'North Africa'), ('central', 'Central Africa')], db_index=True, max_length=20, verbose_name='African Region')),
                ('capital', models.CharField(blank=True, max_length=100, verbose_name='Capital City')),
                ('currency_code', models.CharField(help_text='ISO 4217 currency code', max_length=3, verbose_name='Currency Code')),
                ('currency_name', models.CharField(blank=True, max_length=100, verbose_name='Currency Name')),
                ('currency_symbol', models.CharField(blank=True, max_length=10, verbose_name='Currency Symbol')),
                ('gdp_usd', models.DecimalField(blank=True, decimal_places=2, help_text='GDP in billions USD', max_digits=18, null=True, verbose_name='GDP (USD)')),
                ('population', models.BigIntegerField(blank=True, null=True, verbose_name='Population')),
                ('has_stock_exchange', models.BooleanField(default=False, verbose_name='Has Stock Exchange')),
                ('primary_exchange_code', models.CharField(blank=True, help_text='Primary stock exchange code (e.g., JSE)', max_length=10, verbose_name='Primary Exchange Code')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('flag_emoji', models.CharField(blank=True, max_length=10, verbose_name='Flag Emoji')),
                ('flag_image', models.ImageField(blank=True, null=True, upload_to='flags/', verbose_name='Flag Image')),
                ('is_active', models.BooleanField(default=True, help_text='Include in listings and filters', verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Prominent display in market overview', verbose_name='Featured')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeographicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('level', models.CharField(choices=[('region', 'Region'), ('country', 'Country'), ('city', 'City')], max_length=10, verbose_name='Tag Level')),
                ('region', models.CharField(blank=True, choices=[('southern', 'Southern Africa'), ('eastern', 'East Africa'), ('western', 'West Africa'), ('northern', 'North Africa'), ('central', 'Central Africa')], max_length=20, verbose_name='Region')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_tags', to='geography.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_tags', to='geography.country')),
            ],
            options={
                'verbose_name': 'Geographic Tag',
                'verbose_name_plural': 'Geographic Tags',
            },
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['region'], name='geography_c_region_fa7c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['code'], name='geography_c_code_84f2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['is_active', 'region'], name='geography_c_is_acti_199963_idx'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geography.country'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'slug')},
        ),
    ]
