# Generated by Django 4.2.27 on 2026-01-25 13:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('code', models.CharField(db_index=True, help_text='Unique exchange identifier (e.g., JSE, ZSE)', max_length=10, unique=True, verbose_name='Exchange Code')),
                ('name', models.CharField(help_text='Full name of the exchange', max_length=200, verbose_name='Exchange Name')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('currency', models.CharField(help_text='Trading currency (e.g., ZAR, USD)', max_length=3, verbose_name='Currency')),
                ('timezone', models.CharField(default='Africa/Johannesburg', max_length=50, verbose_name='Timezone')),
                ('trading_hours_start', models.TimeField(default='09:00', verbose_name='Trading Hours Start')),
                ('trading_hours_end', models.TimeField(default='17:00', verbose_name='Trading Hours End')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Sector Code')),
                ('name', models.CharField(max_length=200, verbose_name='Sector Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent sector for hierarchical classification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsectors', to='markets.sector')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Index Code')),
                ('name', models.CharField(max_length=200, verbose_name='Index Name')),
                ('current_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Current Value')),
                ('previous_close', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Previous Close')),
                ('day_high', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Day High')),
                ('day_low', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Day Low')),
                ('ytd_change', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='YTD Change %')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indices', to='markets.exchange')),
            ],
            options={
                'verbose_name': 'Market Index',
                'verbose_name_plural': 'Market Indices',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('symbol', models.CharField(db_index=True, help_text='Stock ticker symbol (e.g., AGL, MTN)', max_length=20, verbose_name='Ticker Symbol')),
                ('isin', models.CharField(blank=True, help_text='International Securities Identification Number', max_length=12, null=True, unique=True, verbose_name='ISIN')),
                ('name', models.CharField(max_length=300, verbose_name='Company Name')),
                ('short_name', models.CharField(blank=True, help_text='Abbreviated company name for display', max_length=100, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Founded Year')),
                ('employees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Employees')),
                ('headquarters', models.CharField(blank=True, max_length=200, verbose_name='Headquarters')),
                ('current_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Current Price')),
                ('previous_close', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Previous Close')),
                ('day_open', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Day Open')),
                ('day_high', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Day High')),
                ('day_low', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Day Low')),
                ('volume', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume')),
                ('market_cap', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Market Cap')),
                ('shares_outstanding', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Shares Outstanding')),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='P/E Ratio')),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dividend Yield %')),
                ('week_52_high', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='52 Week High')),
                ('week_52_low', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='52 Week Low')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the stock is actively trading', verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured on homepage ticker', verbose_name='Featured')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='markets.exchange')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='markets.sector')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='MarketTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('price', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Price')),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Open')),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='High')),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Low')),
                ('close', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Close')),
                ('volume', models.BigIntegerField(default=0, verbose_name='Volume')),
                ('trade_count', models.PositiveIntegerField(default=0, verbose_name='Number of Trades')),
                ('interval', models.CharField(choices=[('tick', 'Tick'), ('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('1d', '1 Day'), ('1w', '1 Week'), ('1M', '1 Month')], db_index=True, default='1d', max_length=10, verbose_name='Interval')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='markets.company')),
            ],
            options={
                'verbose_name': 'Market Ticker',
                'verbose_name_plural': 'Market Tickers',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['company', 'timestamp'], name='markets_mar_company_5118a5_idx'), models.Index(fields=['company', 'interval', 'timestamp'], name='markets_mar_company_9da317_idx'), models.Index(fields=['timestamp'], name='markets_mar_timesta_a449a8_idx')],
                'unique_together': {('company', 'timestamp', 'interval')},
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['symbol'], name='markets_com_symbol_2cbf09_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['exchange', 'symbol'], name='markets_com_exchang_ef5dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active', 'is_featured'], name='markets_com_is_acti_dafde3_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['sector'], name='markets_com_sector__955261_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('symbol', 'exchange')},
        ),
    ]
