# Generated by Django 4.2.27 on 2026-01-25 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('spider_type', models.CharField(choices=[('jse', 'JSE Spider'), ('zse', 'ZSE Spider'), ('bse', 'BSE Spider'), ('news', 'News Spider'), ('forex', 'Forex Spider'), ('indices', 'Indices Spider')], max_length=20, unique=True, verbose_name='Spider')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('schedule_cron', models.CharField(default='*/5 8-17 * * 1-5', help_text='Cron expression for scheduling', max_length=100, verbose_name='Cron Schedule')),
                ('market_hours_only', models.BooleanField(default=True, verbose_name='Market Hours Only')),
                ('market_open', models.TimeField(default='09:00', verbose_name='Market Open')),
                ('market_close', models.TimeField(default='17:00', verbose_name='Market Close')),
                ('min_interval_seconds', models.PositiveIntegerField(default=300, help_text='Minimum seconds between runs', verbose_name='Min Interval (seconds)')),
                ('max_retries', models.PositiveSmallIntegerField(default=3, verbose_name='Max Retries')),
                ('retry_delay_seconds', models.PositiveIntegerField(default=60, verbose_name='Retry Delay (seconds)')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, verbose_name='Timeout (seconds)')),
                ('concurrent_requests', models.PositiveSmallIntegerField(default=1, verbose_name='Concurrent Requests')),
                ('min_items_expected', models.PositiveIntegerField(default=10, help_text='Alert if fewer items scraped', verbose_name='Min Items Expected')),
                ('max_price_change_percent', models.DecimalField(decimal_places=2, default=50, help_text='Flag prices changing more than this %', max_digits=5, verbose_name='Max Price Change %')),
                ('max_volume_change_percent', models.DecimalField(decimal_places=2, default=1000, help_text='Flag volume spikes over this %', max_digits=6, verbose_name='Max Volume Change %')),
                ('alert_on_failure', models.BooleanField(default=True, verbose_name='Alert on Failure')),
                ('alert_on_quality_issue', models.BooleanField(default=True, verbose_name='Alert on Quality Issue')),
                ('alert_email', models.EmailField(blank=True, max_length=254, verbose_name='Alert Email')),
            ],
            options={
                'verbose_name': 'Spider Config',
                'verbose_name_plural': 'Spider Configs',
            },
        ),
        migrations.CreateModel(
            name='SpiderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('spider_type', models.CharField(choices=[('jse', 'JSE Spider'), ('zse', 'ZSE Spider'), ('bse', 'BSE Spider'), ('news', 'News Spider'), ('forex', 'Forex Spider'), ('indices', 'Indices Spider')], max_length=20, verbose_name='Spider')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partial', 'Partial Success')], default='pending', max_length=20, verbose_name='Status')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery Task ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('items_scraped', models.PositiveIntegerField(default=0, verbose_name='Items Scraped')),
                ('items_saved', models.PositiveIntegerField(default=0, verbose_name='Items Saved')),
                ('items_failed', models.PositiveIntegerField(default=0, verbose_name='Items Failed')),
                ('items_duplicates', models.PositiveIntegerField(default=0, verbose_name='Duplicates Skipped')),
                ('requests_made', models.PositiveIntegerField(default=0, verbose_name='Requests Made')),
                ('bytes_downloaded', models.BigIntegerField(default=0, verbose_name='Bytes Downloaded')),
                ('avg_response_time_ms', models.PositiveIntegerField(default=0, verbose_name='Avg Response Time (ms)')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('error_traceback', models.TextField(blank=True, verbose_name='Error Traceback')),
                ('warnings', models.JSONField(default=list, verbose_name='Warnings')),
                ('triggered_by', models.CharField(choices=[('celery_beat', 'Scheduled'), ('manual', 'Manual'), ('api', 'API'), ('retry', 'Retry')], default='celery_beat', max_length=50, verbose_name='Triggered By')),
            ],
            options={
                'verbose_name': 'Spider Job',
                'verbose_name_plural': 'Spider Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['spider_type', '-created_at'], name='spider_spid_spider__440b68_idx'), models.Index(fields=['status', '-created_at'], name='spider_spid_status_f9cdd5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScrapedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('source', models.CharField(choices=[('reuters', 'Reuters'), ('bloomberg', 'Bloomberg'), ('local', 'Local News'), ('press', 'Press Release'), ('gov', 'Government'), ('central_bank', 'Central Bank')], max_length=20, verbose_name='Source')),
                ('source_url', models.URLField(verbose_name='Source URL')),
                ('source_published_at', models.DateTimeField(blank=True, null=True, verbose_name='Source Published At')),
                ('raw_title', models.CharField(max_length=500, verbose_name='Raw Title')),
                ('raw_content', models.TextField(verbose_name='Raw Content')),
                ('raw_excerpt', models.TextField(blank=True, verbose_name='Raw Excerpt')),
                ('raw_author', models.CharField(blank=True, max_length=200, verbose_name='Raw Author')),
                ('raw_image_url', models.URLField(blank=True, verbose_name='Raw Image URL')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='pending', max_length=20, verbose_name='Status')),
                ('quality_score', models.DecimalField(decimal_places=2, default=0, help_text='0-100 score', max_digits=4, verbose_name='Quality Score')),
                ('readability_score', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Readability Score')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Word Count')),
                ('has_image', models.BooleanField(default=False, verbose_name='Has Image')),
                ('detected_topics', models.JSONField(default=list, verbose_name='Detected Topics')),
                ('detected_companies', models.JSONField(default=list, verbose_name='Detected Companies')),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, help_text='-1 (negative) to 1 (positive)', max_digits=4, null=True, verbose_name='Sentiment')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_source', to='news.newsarticle')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content', to=settings.AUTH_USER_MODEL)),
                ('spider_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_content', to='spider.spiderjob')),
            ],
            options={
                'verbose_name': 'Scraped Content',
                'verbose_name_plural': 'Scraped Content',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='spider_scra_status_22807c_idx'), models.Index(fields=['source', '-created_at'], name='spider_scra_source_fe727d_idx'), models.Index(fields=['quality_score'], name='spider_scra_quality_e88e03_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('check_type', models.CharField(choices=[('price_range', 'Price Range Check'), ('volume_spike', 'Volume Spike'), ('missing_data', 'Missing Data'), ('stale_data', 'Stale Data'), ('duplicate', 'Duplicate Detection'), ('anomaly', 'Statistical Anomaly')], max_length=30, verbose_name='Check Type')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=20, verbose_name='Severity')),
                ('company_symbol', models.CharField(blank=True, max_length=20, verbose_name='Symbol')),
                ('field_name', models.CharField(blank=True, max_length=50, verbose_name='Field')),
                ('expected_value', models.CharField(blank=True, max_length=255, verbose_name='Expected')),
                ('actual_value', models.CharField(blank=True, max_length=255, verbose_name='Actual')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(default=dict, verbose_name='Details')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Resolution Note')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_quality_checks', to=settings.AUTH_USER_MODEL)),
                ('spider_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='spider.spiderjob')),
            ],
            options={
                'verbose_name': 'Data Quality Check',
                'verbose_name_plural': 'Data Quality Checks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['check_type', '-created_at'], name='spider_data_check_t_9c8076_idx'), models.Index(fields=['severity', 'is_resolved'], name='spider_data_severit_476f4d_idx'), models.Index(fields=['company_symbol'], name='spider_data_company_b43078_idx')],
            },
        ),
    ]
