# Generated by Django 4.2.27 on 2026-01-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='External URL for featured image (fallback if no uploaded image)', max_length=500, verbose_name='Featured Image URL'),
        ),
    ]
