# Generated by Django 4.2.27 on 2026-01-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_add_featured_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-is_breaking', '-is_featured', '-priority', '-published_at', '-created_at'], 'verbose_name': 'News Article', 'verbose_name_plural': 'News Articles'},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='external_source_name',
            field=models.CharField(blank=True, help_text="Name of external source (e.g., 'Reuters', 'Bloomberg')", max_length=100, verbose_name='Source Name'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='external_url',
            field=models.URLField(blank=True, help_text='Original article URL for aggregated content', max_length=500, verbose_name='External URL'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Higher priority articles appear first (editorial content gets +10)', verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(choices=[('editorial', 'Editorial'), ('newsapi', 'NewsAPI'), ('polygon', 'Polygon.io'), ('scraped', 'Web Scraped'), ('syndicated', 'Syndicated')], db_index=True, default='editorial', help_text='Where the article originated from', max_length=20, verbose_name='Source'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['source', 'status'], name='news_newsar_source_58d05b_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['-priority', '-published_at'], name='news_newsar_priorit_162764_idx'),
        ),
    ]
