# Generated by Django 5.0.14 on 2026-03-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_add_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(choices=[('editorial', 'Editorial'), ('serpapi', 'SerpAPI (Google News)'), ('polygon', 'Polygon.io'), ('scraped', 'Web Scraped'), ('syndicated', 'Syndicated'), ('newsapi', 'NewsAPI')], db_index=True, default='editorial', help_text='Where the article originated from', max_length=20, verbose_name='Source'),
        ),
    ]
