# Generated by Django 5.0.14 on 2026-04-15 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_add_serpapi_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articleview',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='articleview',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='articleview',
            name='country_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Country Name'),
        ),
        migrations.AddField(
            model_name='articleview',
            name='region',
            field=models.CharField(blank=True, max_length=120, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='articleview',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Source'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['-created_at'], name='news_articl_created_04c456_idx'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['article', '-created_at'], name='news_articl_article_6dcc69_idx'),
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['country', '-created_at'], name='news_articl_country_d56ba1_idx'),
        ),
    ]
