# Generated by Django 5.0.14 on 2026-04-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_articleview_city_articleview_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content_type',
            field=models.CharField(choices=[('news', 'News'), ('analysis', 'Analysis'), ('insights', 'Insights'), ('research', 'Research Report'), ('opinion', 'Opinion'), ('earnings', 'Earnings Report')], default='news', max_length=20, verbose_name='Content Type'),
        ),
    ]
