# Generated by Django 5.0.14 on 2026-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_migrate_market_update_to_insights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
