# Generated by Django 5.0.14 on 2026-04-16 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_newsarticle_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes Count'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='saves_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Saves Count'),
        ),
        migrations.CreateModel(
            name='ArticleSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('country', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Country')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='news.newsarticle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article Save',
                'verbose_name_plural': 'Article Saves',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('country', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Country')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.newsarticle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article Like',
                'verbose_name_plural': 'Article Likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', '-created_at'], name='news_articl_article_8938cd_idx'), models.Index(fields=['user', '-created_at'], name='news_articl_user_id_e74047_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='articlelike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('article', 'user'), name='unique_article_like_per_user'),
        ),
        migrations.AddConstraint(
            model_name='articlelike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('session_key', ''), _negated=True)), fields=('article', 'session_key'), name='unique_article_like_per_session'),
        ),
        migrations.AddIndex(
            model_name='articlesave',
            index=models.Index(fields=['article', '-created_at'], name='news_articl_article_b8d533_idx'),
        ),
        migrations.AddIndex(
            model_name='articlesave',
            index=models.Index(fields=['user', '-created_at'], name='news_articl_user_id_3f3a2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='articlesave',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('article', 'user'), name='unique_article_save_per_user'),
        ),
        migrations.AddConstraint(
            model_name='articlesave',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('session_key', ''), _negated=True)), fields=('article', 'session_key'), name='unique_article_save_per_session'),
        ),
    ]
