# Generated by Django 5.0.14 on 2026-04-17 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newsarticle_likes_count_newsarticle_saves_count_and_more'),
        ('users', '0003_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='writer',
            field=models.ForeignKey(blank=True, help_text='Credit goes to this writer instead of the uploading user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='users.writer'),
        ),
    ]
