# Generated by Django 5.0.14 on 2026-02-04 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastShow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('name', models.CharField(max_length=300, verbose_name='Show Name')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Tagline')),
                ('description', models.TextField(help_text='Full show description', verbose_name='Description')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for listings', max_length=300, verbose_name='Short Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='podcasts/shows/covers/', verbose_name='Cover Image')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='podcasts/shows/banners/', verbose_name='Banner Image')),
                ('spotify_url', models.URLField(blank=True, verbose_name='Spotify URL')),
                ('apple_podcasts_url', models.URLField(blank=True, verbose_name='Apple Podcasts URL')),
                ('google_podcasts_url', models.URLField(blank=True, verbose_name='Google Podcasts URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('rss_feed_url', models.URLField(blank=True, verbose_name='RSS Feed URL')),
                ('frequency', models.CharField(blank=True, help_text='e.g., Daily, Weekly, Bi-weekly', max_length=50, verbose_name='Frequency')),
                ('publish_day', models.CharField(blank=True, help_text='e.g., Monday, Tuesday', max_length=20, verbose_name='Publish Day')),
                ('status', models.CharField(choices=[('active', 'Active'), ('hiatus', 'On Hiatus'), ('ended', 'Ended')], default='active', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('total_listens', models.BigIntegerField(default=0, verbose_name='Total Listens')),
                ('subscriber_count', models.PositiveIntegerField(default=0, verbose_name='Subscriber Count')),
            ],
            options={
                'verbose_name': 'Podcast Show',
                'verbose_name_plural': 'Podcast Shows',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PodcastSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('notify_new_episodes', models.BooleanField(default=True, verbose_name='Notify New Episodes')),
            ],
            options={
                'verbose_name': 'Podcast Subscription',
                'verbose_name_plural': 'Podcast Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='EpisodeListen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('listen_duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Listen Duration (seconds)')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Completion %')),
                ('platform', models.CharField(blank=True, help_text='e.g., Web, iOS, Android, Spotify', max_length=50, verbose_name='Platform')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcast_listens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Episode Listen',
                'verbose_name_plural': 'Episode Listens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft-deleted', null=True)),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.SlugField(max_length=500, verbose_name='Slug')),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Episode Number')),
                ('season_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Season Number')),
                ('description', models.TextField(help_text='Episode description/show notes', verbose_name='Description')),
                ('summary', models.CharField(blank=True, help_text='Brief summary for listings', max_length=500, verbose_name='Summary')),
                ('show_notes', models.TextField(blank=True, help_text='Detailed show notes with timestamps', verbose_name='Show Notes')),
                ('transcript', models.TextField(blank=True, help_text='Full episode transcript', verbose_name='Transcript')),
                ('key_topics', models.JSONField(blank=True, default=list, help_text='List of topics discussed with timestamps', verbose_name='Key Topics')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='podcasts/episodes/audio/', verbose_name='Audio File')),
                ('audio_url', models.URLField(blank=True, help_text='External audio URL (e.g., from hosting service)', verbose_name='Audio URL')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or video URL', verbose_name='Video URL')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Duration (seconds)')),
                ('cover_image', models.ImageField(blank=True, help_text='Episode-specific cover (falls back to show cover)', null=True, upload_to='podcasts/episodes/covers/', verbose_name='Episode Cover')),
                ('guests', models.JSONField(blank=True, default=list, help_text='List of guest objects with name, title, organization, bio', verbose_name='Guests')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Published At')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled For')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium Only')),
                ('spotify_episode_id', models.CharField(blank=True, max_length=100, verbose_name='Spotify Episode ID')),
                ('apple_episode_id', models.CharField(blank=True, max_length=100, verbose_name='Apple Episode ID')),
                ('listen_count', models.PositiveIntegerField(default=0, verbose_name='Listen Count')),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Average % of episode listened', max_digits=5, verbose_name='Avg Completion Rate')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('hosts', models.ManyToManyField(blank=True, related_name='podcast_episodes_hosted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Podcast Episode',
                'verbose_name_plural': 'Podcast Episodes',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
