# Generated by Django 5.0.14 on 2026-02-04 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0004_add_comments'),
        ('podcasts', '0001_initial'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='podcast_episodes', to='research.industry'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='related_podcast_episodes', to='news.newsarticle'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='related_research',
            field=models.ManyToManyField(blank=True, related_name='related_podcast_episodes', to='research.researchreport'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='podcast_episodes', to='research.topic'),
        ),
        migrations.AddField(
            model_name='episodelisten',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listens', to='podcasts.podcastepisode'),
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='hosts',
            field=models.ManyToManyField(blank=True, related_name='podcast_shows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='podcast_shows', to='research.industry'),
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='podcast_shows', to='research.topic'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.podcastshow'),
        ),
        migrations.AddField(
            model_name='podcastsubscription',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='podcasts.podcastshow'),
        ),
        migrations.AddField(
            model_name='podcastsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='podcastshow',
            index=models.Index(fields=['slug'], name='podcasts_po_slug_8fe1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='podcastshow',
            index=models.Index(fields=['status', 'is_featured'], name='podcasts_po_status_2222c3_idx'),
        ),
        migrations.AddIndex(
            model_name='podcastepisode',
            index=models.Index(fields=['show', 'status'], name='podcasts_po_show_id_acc9a7_idx'),
        ),
        migrations.AddIndex(
            model_name='podcastepisode',
            index=models.Index(fields=['status', 'published_at'], name='podcasts_po_status_41a4b7_idx'),
        ),
        migrations.AddIndex(
            model_name='podcastepisode',
            index=models.Index(fields=['is_featured', 'status'], name='podcasts_po_is_feat_604996_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='podcastepisode',
            unique_together={('show', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='podcastsubscription',
            unique_together={('user', 'show')},
        ),
    ]
