# Generated by Django 4.2.27 on 2026-01-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('from_path', models.CharField(help_text='Path without domain, e.g., /old-article', max_length=500, unique=True, verbose_name='From Path')),
                ('to_path', models.CharField(help_text='Path or full URL', max_length=500, verbose_name='To Path')),
                ('redirect_type', models.IntegerField(choices=[(301, '301 Permanent'), (302, '302 Temporary'), (303, '303 See Other'), (307, '307 Temporary'), (308, '308 Permanent')], default=301, verbose_name='Redirect Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_regex', models.BooleanField(default=False, help_text='Treat from_path as regex pattern', verbose_name='Use Regex')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='Hit Count')),
                ('last_hit', models.DateTimeField(blank=True, null=True, verbose_name='Last Hit')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
                'ordering': ['from_path'],
            },
        ),
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('site', models.CharField(default='default', max_length=100, unique=True, verbose_name='Site')),
                ('content', models.TextField(default='User-agent: *\nAllow: /\n\nSitemap: https://example.com/sitemap.xml\n', verbose_name='Content')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Robots.txt',
                'verbose_name_plural': 'Robots.txt',
            },
        ),
        migrations.CreateModel(
            name='StructuredData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('schema_type', models.CharField(choices=[('Article', 'Article'), ('NewsArticle', 'News Article'), ('AnalysisNewsArticle', 'Analysis News Article'), ('Person', 'Person'), ('Organization', 'Organization'), ('WebSite', 'Website'), ('BreadcrumbList', 'Breadcrumb List'), ('FAQPage', 'FAQ Page'), ('Product', 'Product'), ('Event', 'Event')], max_length=50, verbose_name='Schema Type')),
                ('template', models.JSONField(help_text='JSON-LD template with placeholders', verbose_name='Template')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Structured Data Template',
                'verbose_name_plural': 'Structured Data Templates',
            },
        ),
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('object_id', models.PositiveIntegerField()),
                ('meta_title', models.CharField(blank=True, help_text='Optimal: 50-60 characters', max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='Optimal: 150-160 characters', max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, verbose_name='Meta Keywords')),
                ('canonical_url', models.URLField(blank=True, help_text='Leave blank to use default URL', verbose_name='Canonical URL')),
                ('no_index', models.BooleanField(default=False, help_text='Prevent search engines from indexing', verbose_name='No Index')),
                ('no_follow', models.BooleanField(default=False, help_text='Prevent search engines from following links', verbose_name='No Follow')),
                ('og_title', models.CharField(blank=True, max_length=95, verbose_name='OG Title')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, help_text='Recommended: 1200x630px', null=True, upload_to='seo/og/', verbose_name='OG Image')),
                ('og_type', models.CharField(choices=[('article', 'Article'), ('website', 'Website'), ('profile', 'Profile'), ('book', 'Book')], default='article', max_length=50, verbose_name='OG Type')),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', max_length=50, verbose_name='Twitter Card Type')),
                ('twitter_title', models.CharField(blank=True, max_length=70, verbose_name='Twitter Title')),
                ('twitter_description', models.CharField(blank=True, max_length=200, verbose_name='Twitter Description')),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='seo/twitter/', verbose_name='Twitter Image')),
                ('sitemap_priority', models.DecimalField(decimal_places=1, default=0.5, help_text='0.0 to 1.0', max_digits=2, verbose_name='Sitemap Priority')),
                ('sitemap_changefreq', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='weekly', max_length=20, verbose_name='Change Frequency')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='seo_seometa_content_a438cb_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
